### ISSUE TITLE
Transfer of the "url-tools" npm package

### ISSUE THREAD

**Issue by JasonLandbridge** [glennjones/url-tools#1]
Hi Glenn, 

I am currently developing a library to transform urls in various ways and I was hoping I could take over the [url-tools](https://www.npmjs.com/package/url-tools) npm registry. 

My url-tools can be found [here](https://github.com/Url-Tools/Url-Tools)

I would also be more than happy to integrate the normalize function from this repo into my url-tools. 

Thanks in advance!

**Comment by glennjones** [comment]
Hi Jason

Had a long hard think about your request. The module is used by an old
client of mine in a legacy product. Although rarely pulled, I am not overly
happy about giving up the ownership. It sort of breaks the chain of trust
under which it was originally used in their work. If it was not for this I
would have considered this as I don't want to sit on things I am no longer
actively developing and only using rarely.

You can always release it on npm under @jasonlandbridge/
<https://github.com/JasonLandbridge/FluentTypeResults>url-tools

Happy to discuss it further if you want

Glenn

**Comment by JasonLandbridge** [comment]
Hi Glenn, 

Thanks for the reply!
 
I completely understand where you're coming from and I see the responsibility you have to your clients. In the end a name doesn't matter much so I've gone ahead and followed your advice and published my package under [@jasonlandbridge/url-tools](https://www.npmjs.com/package/@jasonlandbridge/url-tools). 

Best of luck, 
Jason
